-- Your SQL goes here
CREATE TABLE dyn_paths (
  id SERIAL PRIMARY KEY,
  nonce NONCE NOT NULL,  -- METADATA, 
  guarantee ACCOUNT NOT NULL,  -- METADATA, 
  guarantor ACCOUNT NOT NULL,  -- METADATA, 
  signature SIGNATURE NOT NULL UNIQUE,  -- METADATA, 
  created_date TIMESTAMP NOT NULL,  -- METADATA, 
  expiration_date TIMESTAMP,  -- METADATA, 
  kind SHA256HASH NOT NULL,
  word SHA256HASH NOT NULL,
  path SHA256HASH NOT NULL,
  len BIGINT NOT NULL
);
